# Generated by Django 5.1.1 on 2025-01-21 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdExtraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='in_moderation', max_length=14, verbose_name='status')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ad_extra', to='store.ad', verbose_name='ad')),
            ],
            options={
                'verbose_name': 'Ad Extra Info',
                'verbose_name_plural': 'Ad Extra Infos',
            },
        ),
    ]
